# Generated by Django 4.2.1 on 2023-06-19 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('no', models.IntegerField()),
                ('game_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('players', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('cup_name', models.CharField(max_length=100)),
                ('game_name', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='app.game')),
            ],
        ),
    ]
